language: node_js
node_js: stable

matrix:
  include:
    - env:
      - TASK=build
      script: 
        - npm install

deploy:
  provider: script
  script: bash .deploy.sh
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = "false" && $TASK = "build"
